### PR TITLE
Hours Notation, Milestones, and Options Menu

### PR DESCRIPTION
**Pull request by monk125**
I added an option to output the total combined time as a number of hours, rather than days/hours/minutes/seconds. This involved passing a new parameter to `secondsToDhms()`, which in turn has the option of accessing a new `pluralize_unit` function (which handles floats) instead of `check_plural`

I also added what I'm calling Milestone tracking. The user can click a button to track total combined time from a new point in addition to the total time of the whole project. Up to 2 additional points can be saved at a time. Uses:

- More holistic session timers (I have the need to reload the project semi-frequently, so Current/Last session don't always reflect my work day particularly well.)
- Track workweeks/months/pay periods
- Track devtime of smaller features

To support this `total_active_time()` now takes a parameter to know whether it's checking TT, M1, or M2 time

I also also (I know, terrible form, I'm new here, forgive me) added an Options menu to control the visibility of all the new stuff I added, as well as all the old stuff as long as I was mucking around with it. All parts of the tracker can be hidden except for the "Show Options" checkbox, to enable greater user customization and reduce clutter.

Here's what the final product looks like:

image

### CODE REVIEW

**Comment by victormajida** [comment]
Looking good, thanks for the update. Just a few notes:
. Since the show options checkbox can't be hidden, might as well make it a button which changes label to "hide options" once options are shown. 

. Can you explain a bit more about the milestone functionality? In your screenshot, what happens when I click on "Set Milestone 1" or "Set Milestone 2", does it automatically create a new "Time Since" with "Set Milestone 3"?

**Comment by monk125** [comment]
- Suggestion taken: Show Options is now a button.

- No, there's only ever 2 milestones tracked in this implementation. Clicking the button merely overrides the previous milestone. For example, before and after pushing the M1 button:
image image

(And for completeness, what the Show Options button looks like when the options are hidden):

image


Having a single button that adds milestones while replacing the "set milestone" buttons with "remove this milestone" would certainly be a more elegant and robust solution, but also more than I needed.

My initial plan was to actually have calculations for things like "time project was open over last 18 hours, over last 7 calendar days, etc" to track things like workdays and workweeks and so forth. But, that sounded hard, and what my milestone implementation lacks in elegance it makes up for in versatility.

**Comment by victormajida** [comment]
> Suggestion taken: Show Options is now a button.
Looks good, thank you.

Regarding the milestones, maybe the wording is confusing to me. Also the fact there are 2, my mind is thinking why not more, or just one...
I don't mean to be that guy but can you give me an example of how the milestones functionality has helped? It may help understand better its need.
In the meantime if you want to push a different branch for the "Options", I'll merge it 👍

**Comment by monk125** [comment]
The reason there are 2 milestones (rather than 1, or N) is because I was too lazy/shortsighted to implement the functionality to make it scalable, and 2 is sufficient for my needs (I normally only use one.)

My primary use for the milestone feature is to track how long my workday is/was/has been. In principle this is what the Last Session tab is for, but I find that insufficient for my needs for a couple reasons:

1. My workday does not consist of a single 6-10 hour work day, but rather multiple 1-3 hour chunks. When I have a full day to work on my project, I usually have multiple sessions of coding, and Last Session only tells me what the prior session was.

2. Current Session does not survive pressing the "Reload Current Project" button in the editor, which I find I have to do semi-regularly (usually because Godot is not updating the autocomplete features, and I make numerous typos without autocomplete.) This means that even on days when I'm squeezing an hour or two in on the project after my day job, I can't rely on Current/Last Session to tell me how long I've been at it.


So now, when my workday starts I push the "Set Milestone" button. It does not then matter if I need to Reload the project or just take breaks to run errands, the Milestone tracker will keep adding the combined time since I hit that button. At the end of the night, I can look and see how much actual time that day was spent in the editor.

I added the second tracker because I can think of enough uses for the feature to warrant tracking multiple milestones at once. Apart from other arbitrary time tracking periods (weekly, monthly) I can see myself using the second milestone to track things like the time I spend on a specific feature in the project, or on a code refactor, or "I'm going to do 10 hours of bugfixing before I go back to the fun stuff," etc.


It could certainly be handled more elegantly, but it works for me. It's no big deal if you don't want to merge it, just thought you might like to see what I did with it.

**Comment by victormajida** [comment]
Ok I see. 
Thanks for taking the time to explain. I think I like the fact it stays simple (2 instead of N).

**Pull request merged**
